import './globals.css'
import { Metadata } from 'next'
import Head from 'next/head';  // Head 컴포넌트를 임포트

export const metadata: Metadata = {
  title: 'shinleehyun',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <Head>
        <meta name="google-site-verification" content="U3XR0SbCLhek7REd-BeocPYDC8CP7GqVe_elyQn4GLg" />
        <title>shinleehyun</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>{children}</body>
    </html>
  )
}
