import './globals.css'
import { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'shinleehyun',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}